/* eslint-disable react/jsx-filename-extension */
import {
  Avatar, Chip, Divider, List, ListItem, ListItemAvatar, ListItemText, Typography,
} from '@mui/material';
import React from 'react';

const imageUrl1 = 'https://nft-trading-market-object-storage.sfo3.digitaloceanspaces.com/Images/NFT_marketplace.ico';
const imageUrl2 = 'https://nft-trading-market-object-storage.sfo3.digitaloceanspaces.com/Images/nft2.webp';
const imageUrl3 = 'https://nft-trading-market-object-storage.sfo3.digitaloceanspaces.com/Images/nft2.jpeg';
function NftSale() {
  return (
    <>
      <Typography variant="h5">
        <strong>NFT Sale</strong>
      </Typography>
      <List sx={{ width: '100%', maxWidth: 1000, bgcolor: 'background.paper' }}>
        <ListItem alignItems="flex-start">
          <ListItemAvatar>
            <Avatar alt="Remy Sharp" src={imageUrl1} />
          </ListItemAvatar>
          <ListItemText
            primary="NFT Name"
            secondary={(
              <>
                <Typography
                  sx={{ display: 'inline' }}
                  component="span"
                  variant="body2"
                  color="text.primary"
                >
                  Ali Connors
                </Typography>
                {' — NFT description'}
              </>
          )}
          />
        </ListItem>

        <Divider variant="inset" component="li" />

        <ListItem alignItems="flex-start">
          <ListItemAvatar>
            <Avatar alt="Travis Howard" src={imageUrl2} />
          </ListItemAvatar>
          <ListItemText
            primary="Summer BBQ"
            secondary={(
              <>
                <Typography
                  sx={{ display: 'inline' }}
                  component="span"
                  variant="body2"
                  color="text.primary"
                >
                  to Scott, Alex, Jennifer
                </Typography>
                {" — Wish I could come, but I'm out of town this…"}
              </>
          )}
          />
          {' '}
          <Chip variant="outlined" label="Auctioned" color="primary" style={{ marginRight: '10px' }} clickable />
          <Typography variant="p">
            Latest bid - srthkmr491
            {' '}
            <br />
            Price offered - 1.34BTC
          </Typography>
        </ListItem>

        <Divider variant="inset" component="li" />

        <ListItem alignItems="flex-start">
          <ListItemAvatar>
            <Avatar alt="Cindy Baker" src={imageUrl3} />
          </ListItemAvatar>
          <ListItemText
            primary="gun_smith_nft"
            secondary={(
              <>
                <Typography
                  sx={{ display: 'inline' }}
                  component="span"
                  variant="body2"
                  color="text.primary"
                >
                  Body Snatchers Collection
                </Typography>
                {' — The Body Snatchers is a collection of 2000 unique ERC-721 tokens living on the Polygon Blockchain. Minting has been realised in 50 rounds , 40 Snatchers each round . Price will grow for 0.02ETH after a batch sold. Every week we add in pool 8ETH . Each NFT generated by alghoritmic smart contract comes with a full membership to an ever-growing community and awesome utilities.'}
              </>
          )}
          />
        </ListItem>
      </List>
    </>
  );
}

export default NftSale;
